### ISSUE TITLE
Auto Smelt Wand

### ISSUE THREAD

**Issue by l5v** [Tantillus-BITMC/ReimannMC-Minecraft-server#11]
Maybe a wand that smelts everything in a chest, for example the iron dosnt automatically smelt

**Comment by Tantillus-KW1C** [comment]
There are quite some tutorials on youtube on how to make an automatic smelting system! I personally advise watching MumboJumbo’s tutorial on this matter. 

This issue will receive the “wontfix” tag for now, but will be reopened if more people start suggesting a feature such as the one you described.

Thanks alot!

~Tantillus
  Developer
