### ISSUE TITLE
Shop/Farming Suggestion

### ISSUE THREAD

**Issue by Punchie15** [Tantillus-BITMC/ReimannMC-Minecraft-server#13]
Making custom recipes can be another way to grind farms and make money, and giving players more ways to enjoy grinding when they have majority of the usual stuff completed.

**Comment by Tantillus-KW1C** [comment]
Could you elaborate on these subjects:

>  Making custom recipes

> Majority of the usual stuff completed.

Are you suggesting we should introduce crafting recipe's to the server that don't exist in the vanilla game?

~ Tantillus

**Comment by Punchie15** [comment]
Yeah that is what Im saying, as an example I would say one crafting recipe could be _Smoked Salmon_ where you need _Coal x2_ _Cooked Salmon x1_. Or _Undead Mushroom_ which could need _Rotten Flesh x3, Any Mushroom x2 and Nether Wart x1_ which obviously these custom recipes would sell for a lot more than the vanilla items would cost. Also on top of this to include custom recipes to a new update, I would suggest loot boxes or contraband chests being added into the envoy at /warp pvp, and in these lootboxes/contraband chests could have many items in it including the recipe pages of the custom recipe in which you could redeem. These could work the same way as the Vote Crates work, where there is a certain percentage per item you can get, so lets say there is maybe 20 items in these new contrabands/lootboxes, they are randomised to where you get 4 items out of the 20 possible outcomes. Hopefully this makes you understand what I am trying to say a little bit more.

~ Punchie
