### ISSUE TITLE
/shop suggestion

### ISSUE THREAD

**Issue by l5v** [Tantillus-BITMC/ReimannMC-Minecraft-server#4]
I think that you should make it so we can buy more then one stack without it kicking you from the menu because i need over 10 stacks of wood and i have to keep clicking over and over.

**Comment by Tantillus-KW1C** [comment]
Will start development on this! Thanks for the suggestion.

~Tantillus

**Comment by Tantillus-KW1C** [comment]
Your suggestion was linked to our project board, and this ticket will be closed.
