### ISSUE TITLE
Overload V books.

### ISSUE THREAD

**Issue by Punchie15** [Tantillus-BITMC/ReimannMC-Minecraft-server#7]
The overload V books you get with your /gkit when placed into your /pv turns into a regular book.

**Comment by Tantillus-KW1C** [comment]
Does this explicitly happen with the Overload V books, or also other enchantments that aren't 'vanilla' minecraft?

**Comment by Punchie15** [comment]
I have not tried with other books yet. But I will let you know once I get online.

**Comment by l5v** [comment]
It does.

**Comment by Tantillus-KW1C** [comment]
Hey,

I'm sorry to inform you, @l5v and @Punchie15 that this issue can't be fixed.

Items with a custom name or lore, can be lost randomly in your pv.
Please refer to [this (click)](https://github.com/drtshock/PlayerVaults/issues/353) issue on the PlayerVaults Github page for more details about the issue.

I'll be contacting a few plugin developers that maybe can produce a fix for this issue. 

**I strongly reccomend you to not place any items with a custom title/lore in your /pv.**
