### ISSUE TITLE
Mobs spawning on island

### ISSUE THREAD

**Issue by l5v** [Tantillus-BITMC/ReimannMC-Minecraft-server#8]
I think that there should be an option or completely turn off mob spawning on the island at least when it's dark, I'm just trying to build a grinder and I can't because there are 100+ mobs here.

**Comment by Tantillus-KW1C** [comment]
Hey,

Thanks for the suggestion. 

Having an option that simply disables the possibility of mobs to spawn at all will also leave your (other) mobspawners useless.

This is a known issue, we just haven't gotten around to fixing it yet.
What we would need is a option that only disabled the natural spawn event to be disabled on your/any island. 

We're looking for a feature that allows this, we just haven't found it yet.

Thanks for the ticket though!

~Tantillus
  Server Dev

**Comment by Tantillus-KW1C** [comment]
Your ticket was linked to our project board, closing this ticket.
